<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="IHD-1ZMHBX1" name="Sunrise Springs Resort1" tests="1" failures="1" timestamp="8 Jun 2016 08:31:40 GMT" time="1.289" errors="0">
  <testcase name="@AfterClass stop" time="0.0" classname="innRoad.suite.Booking_Engine">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at innRoad.config.BaseTest.setupAfterSuite(BaseTest.java:139)
	at innRoad.suite.Booking_Engine.stop(Booking_Engine.java:2249)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- @AfterClass stop -->
  <testcase name="testUntitled" time="0.024" classname="innRoad.suite.Booking_Engine">
    <failure type="java.lang.IllegalArgumentException" message="The workbook already contains a sheet of this name">
      <![CDATA[java.lang.IllegalArgumentException: The workbook already contains a sheet of this name
	at org.apache.poi.hssf.usermodel.HSSFWorkbook.createSheet(HSSFWorkbook.java:750)
	at innRoad.config.BaseTest.setupBeforeSuite(BaseTest.java:124)
	at innRoad.suite.Booking_Engine.testUntitled(Booking_Engine.java:93)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- testUntitled -->
</testsuite> <!-- Sunrise Springs Resort1 -->
